### ISSUE TITLE
portability with shellcheck

### ISSUE THREAD

**Issue by ngadmini** [Tontonjo/proxmox_toolbox#13]
hi @Tontonjo 

```shell
apt update
apt install shellcheck
shellcheck proxmox_toolbox.sh
```
see what happen

regards,
nGadmini binti nGadimin

**Comment by Tontonjo** [comment]
Hey!
Thanks you for checking Proxmox Toolbox.
I've heard about spellcheck and already had it run on Proxmox Toolbox.
Lots of things to improve for sure. The toolbox is missing a lot of comment aswell.

Since i dont have much time and it's working as-is, it's not a real issue

This will for sure be corrected sometimes tho.
