### ISSUE TITLE
Change E-Mail From Name

### ISSUE THREAD

**Issue by Skyfay** [Tontonjo/proxmox_toolbox#18]
Hey,
Thanks for the script!

Today i have a question about the SMTP Module. 
I have configured it, but the emails always arrive as `root <mail@example.com>`. 
Is there a way to change the `root` part to something else?

I allready tried to edit the canonical file and make a postmap but that didn't work as expected.

**Comment by Tontonjo** [comment]
Hey,

Not sure to remember well the whole thing, but if my memory does not fails me, the problem is that the mail are sent by root (the system) and as far as  i know, it's not that simple to change this: you have to "rewrite" the address.

I re-digged a bit to refresh my memory, and it looks like you have to edit  /etc/postfix/generic to do this, according to: [https://unix.stackexchange.com/questions/281955/postfix-smarthost-sends-as-root](this stackexchange thread).

You may want to try on your system and tell me if this is working as expected.
Did some tests on my own system right now without success at the moment, may dig into it later or fire up my lab pve installation.

I'm keeping this issue open as this may be a good thing to improve.

Regards

**Comment by Tontonjo** [comment]
Ok i managed to succeed. I faced some strange behavior as my emails were not being received on Gmail but i felt my configurations was OK as i've tested my regex and all settings: looks like Gmail blacklisted me for a while as the test works on my O365 Account but not anymore on gmail.

Will set the hostname as sender name

**Comment by Tontonjo** [comment]
fixed

Thanks for your suggestion.
